/* Council UI prototype. No inference, authentication or payment requests. */
(() => {
 'use strict';
 const {scenarios,matchScenario,textResult,sanitizeSaved}=globalThis.CouncilBetaData;
 const {models,defaults,packs,normalizeSelection,validSelection}=globalThis.CouncilConfig;
 const $=id=>document.getElementById(id);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const storage={get(k,defaultValue){try{const v=localStorage.getItem('council-beta:'+k);return v===null?defaultValue:JSON.parse(v);}catch{return defaultValue;}},set(k,v){try{localStorage.setItem('council-beta:'+k,JSON.stringify(v));return true;}catch{return false;}}};
 let saved=sanitizeSaved(storage.get('saved',[])), current='mvp', runGeneration=0, timers=[], view='home', toastTimer, opener=null, draftStored=true;
 let selection=normalizeSelection(storage.get('models',defaults)), runSelection=[...selection];
 const modal=$('modal'),modalBody=$('modal-body');
 function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
 function cancelRun(){runGeneration++;timers.forEach(clearTimeout);timers=[];}
 function closeMenu(){if(!$('sidebar'))return;$('sidebar').classList.remove('open');$('scrim').hidden=true;$('open-menu').setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');document.querySelector('.app-shell').inert=false;}

 function selectedModels(ids=selection){return models.filter(m=>ids.includes(m.id));}
 function memberCount(n){return n+' участник'+(n===1?'':n>=2&&n<=4?'а':'ов');}
 function marks(ids){return selectedModels(ids).map(m=>`<span class="model-mark"><img src="${m.image}" alt="${esc(m.name)}" width="22" height="22"></span>`).join('');}
 function boardCards(ids,scope,large=false){return models.map(m=>`<label class="board-card ${ids.includes(m.id)?'selected':''} ${large?'catalog-card':''}" data-card="${m.id}"><input type="checkbox" name="council-model" value="${m.id}" ${ids.includes(m.id)?'checked':''} aria-label="${esc(m.name)}"><span class="board-icon"><img src="${m.image}" width="30" height="30" alt=""></span><span class="board-copy"><strong>${esc(m.name)}</strong><small>${esc(m.provider)}</small>${large?`<span>${esc(m.caption)}</span>`:''}</span><span class="board-check" aria-hidden="true"><svg viewBox="0 0 16 16"><path d="m3 8 3 3 7-7"/></svg></span></label>`).join('');}
 function syncRoster(){
  $('roster-button').innerHTML=`<span class="roster-marks" aria-hidden="true">${marks(selection)}</span><span>Модели · ${selection.length}</span><span aria-hidden="true">⌄</span>`;
  $('roster-button').setAttribute('aria-label','Выбрать модели. Сейчас: '+selectedModels().map(m=>m.name).join(', '));
 }
 function applySelection(ids){
  if(!validSelection(ids))return false;
  selection=normalizeSelection(ids);
  const savedOk=storage.set('models',selection);syncRoster();
  if(!savedOk)toast('Состав изменён. Браузер не разрешил сохранить его после закрытия.');
  return true;
 }
 function mountPicker(root,{dismiss=false}={}){
  let draft=[...selection];
  root.innerHTML=`<div class="picker-summary"><span>Выберите <strong>2–4 модели</strong></span></div><div class="picker-grid">${boardCards(draft,'picker',true)}</div><p class="picker-error field-error" role="status" hidden>Для обсуждения нужны как минимум два участника.</p><div class="picker-bottom"><span class="picker-count">${memberCount(draft.length)}</span><button class="primary-button" data-apply-composition>Готово</button></div>`;
  const grid=root.querySelector('.picker-grid'),button=root.querySelector('[data-apply-composition]');
  function update(){draft=[...grid.querySelectorAll('input:checked')].map(n=>n.value);grid.querySelectorAll('[data-card]').forEach(n=>n.classList.toggle('selected',draft.includes(n.dataset.card)));root.querySelector('.picker-count').textContent=memberCount(draft.length);root.querySelector('.picker-error').hidden=validSelection(draft);button.disabled=!validSelection(draft);}
  grid.querySelectorAll('input').forEach(n=>n.onchange=update);
  button.onclick=()=>{if(!applySelection(draft))return;if(dismiss)closeDialog();toast('Состав совета сохранён');};
 }
 function renderSidebar(){
  $('saved-section').hidden=!saved.length;
  $('saved-nav').innerHTML=saved.map(v=>`<button class="side-item ${view==='result'&&current===v.id?'active':''}" data-result="${v.id}" data-team="${v.modelIds.join(',')}">${esc(scenarios[v.id].nav)}</button>`).join('');
 }
 function setView(next,{focus=true}={}){
  if(next!=='run')cancelRun();view=next;['home','run','result','error','page'].forEach(v=>{const n=$(v+'-view');if(n)n.hidden=v!==next;});
  $('page-label').textContent={home:'Новое обсуждение',run:'Обсуждение',result:'Результат',error:'Обсуждение',page:document.body.dataset.title||'Council'}[next];
  if(!document.body.dataset.page&&next!=='result')updateAddress(null);
  document.title=$('page-label').textContent+' — Council';
  renderSidebar();closeMenu();if(focus){window.scrollTo(0,0);$('main').focus({preventScroll:true});}
 }
 function updateAddress(id){try{const url=new URL(location.href);url.searchParams.delete('preset');url.searchParams.delete('example');url.searchParams.delete('team');if(id){url.searchParams.set('example',id);url.searchParams.set('team',runSelection.join(','));}history.replaceState(null,'',url);}catch{}}
 function updateDraftStatus(){const message=!draftStored?'Не удалось сохранить черновик в браузере.':$('question').value||$('context').value?'Черновик сохранён в этой вкладке.':'';if($('draft-status').textContent!==message)$('draft-status').textContent=message;}
 function setDraft(){try{sessionStorage.setItem('council-beta:draft',JSON.stringify({question:$('question').value,context:$('context').value}));draftStored=true;}catch{draftStored=false;}updateDraftStatus();return draftStored;}
 function setContextOpen(open){$('context-fields').hidden=!open;$('context-toggle').setAttribute('aria-expanded',String(open));$('context-toggle').innerHTML=open?'<span aria-hidden="true">−</span> Контекст':'<span aria-hidden="true">＋</span> Контекст';}
 function restoreDraft(){try{const d=JSON.parse(sessionStorage.getItem('council-beta:draft')||'null');if(d&&typeof d.question==='string'){$('question').value=d.question.slice(0,6000);$('context').value=typeof d.context==='string'?d.context.slice(0,3000):'';}}catch{draftStored=false;}setContextOpen(Boolean($('context').value));updateDraftStatus();}
 function hasCustomDraft(){return Boolean(($('question').value.trim()||$('context').value.trim())&&!matchScenario($('question').value,$('context').value));}
 function confirmReplacement(action){if(!hasCustomDraft()){action();return;}closeMenu();dialogFrame('Заменить ваш черновик?','<p>В поле уже есть собственный вопрос. При продолжении он будет заменён. Можно вернуться и скопировать его.</p><div class="modal-actions"><button class="secondary-button" data-close>Оставить черновик</button><button class="primary-button" id="replace-draft">Заменить</button></div>');$('replace-draft').onclick=()=>{closeDialog();action();};}
 function returnToQuestion(){if(document.body.dataset.page){location.href='beta.html';return;}setView('home');$('question').focus();}
 function newDiscussion(){confirmReplacement(()=>{$('question').value='';$('context').value='';$('question-error').hidden=true;$('question').removeAttribute('aria-invalid');setContextOpen(false);setDraft();returnToQuestion();});}
 function prefill(id){if(!Object.hasOwn(scenarios,id))return;confirmReplacement(()=>{current=id;if(document.body.dataset.page){$('question').value=scenarios[id].question;$('context').value=scenarios[id].context;setDraft();location.href='beta.html';return;}setView('home');$('question').value=scenarios[id].question;$('context').value=scenarios[id].context;$('question-error').hidden=true;$('question').removeAttribute('aria-invalid');setContextOpen(Boolean($('context').value));setDraft();$('question').focus();});}
 function byline(i,small){return `<div class="model-byline"><span class="participant-mark" aria-hidden="true">${['A','B','C','D'][i]||'A'}</span><div><strong>Позиция ${i+1}</strong><small>${esc(small)}</small></div></div>`;}
 function updateStage(stage){document.querySelectorAll('[data-stage]').forEach(n=>{const v=Number(n.dataset.stage);n.classList.toggle('current',v===stage);n.classList.toggle('done',v<stage);if(v===stage)n.setAttribute('aria-current','step');else n.removeAttribute('aria-current');});$('run-status-text').textContent=['Показываем независимые позиции','Показываем проверку важного возражения','Собираем пример общего вывода'][stage];$('challenge-card').hidden=stage===0;}
 function start(id=current){
  if(!Object.hasOwn(scenarios,id))return;cancelRun();current=id;runSelection=[...selection];const generation=runGeneration,s=scenarios[id];setView('run');$('run-heading').textContent=s.question;$('run-context').textContent=s.context;
  $('run-roster').innerHTML='<span>Состав интерфейса</span>'+marks(runSelection);
  $('position-cards').innerHTML=s.positions.slice(0,runSelection.length).map((p,i)=>`<article class="position-card">${byline(i,'Независимая позиция · пример')}<p>${esc(p)}</p></article>`).join('');
  $('challenge-card').innerHTML=`<h2>Замечание, которое меняет план</h2><p>${esc(s.challenge)}</p>`;updateStage(0);
  const schedule=(fn,delay)=>timers.push(setTimeout(()=>{if(generation===runGeneration&&view==='run')fn();},delay));
  schedule(()=>updateStage(1),2600);schedule(()=>updateStage(2),5300);schedule(()=>showResult(id),7100);
 }
 function activateTab(name,focus=false){for(const key of ['summary','discussion']){const active=key===name;$(key+'-tab').setAttribute('aria-selected',String(active));$(key+'-tab').tabIndex=active?0:-1;$(key+'-panel').hidden=!active;}if(focus)$(name+'-tab').focus();}
 function showResult(id=current,team=selection){
  if(!Object.hasOwn(scenarios,id))return;if(document.body.dataset.page){location.href='beta.html?example='+encodeURIComponent(id)+'&team='+encodeURIComponent(normalizeSelection(team).join(','));return;}current=id;if(view!=='run')runSelection=normalizeSelection(team);const s=scenarios[id];setView('result');updateAddress(id);document.title=s.nav+' — Council';$('result-heading').textContent=s.title;$('result-question').textContent=s.question;
  $('summary-panel').innerHTML=`<article class="recommendation"><h2>Рекомендация</h2><p>${esc(s.recommendation)}</p></article><section class="answer-section"><h2 class="section-title">Почему этот вариант</h2><ol class="reason-list">${s.reasons.map((r,i)=>`<li><span class="reason-index">0${i+1}</span><span>${esc(r)}</span></li>`).join('')}</ol></section><section class="answer-section"><h2 class="section-title">Что изменилось после проверки</h2><div class="change-grid"><div><small>Первоначальный вариант</small><p>${esc(s.before)}</p></div><div><small>После замечания</small><p>${esc(s.after)}</p></div></div></section><section class="answer-section"><h2 class="section-title">Осталось открытым</h2><div class="unresolved">${esc(s.disagreement)}</div></section><section class="answer-section"><h2 class="section-title">Следующий шаг</h2><p class="next-step">${esc(s.next)}</p></section>`;
  $('result-member-count').textContent=memberCount(runSelection.length);$('discussion-tab').querySelector('span').textContent=String(runSelection.length+2);
  $('discussion-panel').innerHTML=`${s.positions.slice(0,runSelection.length).map((p,i)=>`<article class="exchange">${byline(i,'Независимая позиция · пример')}<p>${esc(p)}</p></article>`).join('')}<article class="exchange">${byline(1,'Существенное возражение')}<p>${esc(s.challenge)}</p><blockquote>Проверяем первоначальный вариант: ${esc(s.before)}</blockquote></article><article class="exchange">${byline(0,'Уточнение позиции')}<p>${esc(s.reply)}</p></article><p class="storage-note">Готовый пример. Реплики подготовлены заранее, не получены от выбранных AI.</p>`;
  $('save-result').textContent=saved.some(v=>v.id===id)?'Сохранено':'Сохранить';activateTab('summary');
 }
 function dialogFrame(title,html){if(!modal.open)opener=document.activeElement;modalBody.innerHTML=`<h2 id="modal-title" tabindex="-1">${esc(title)}</h2>${html}`;if(!modal.open){modal.showModal();document.body.classList.add('modal-open');}$('modal-title').focus({preventScroll:true});}
 function closeDialog(){if(modal.open)modal.close();}
 modal.addEventListener('close',()=>{document.body.classList.remove('modal-open');modalBody.querySelectorAll('input').forEach(n=>n.value='');const needsFocus=document.activeElement===document.body||modal.contains(document.activeElement);if(needsFocus&&opener?.isConnected&&!opener.closest('[hidden]')&&!modal.open)opener.focus({preventScroll:true});});
 $('close-modal').addEventListener('click',closeDialog);modal.addEventListener('click',e=>{if(e.target!==modal)return;const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();});
 function showDialog(kind){
  if(kind==='quote'){dialogFrame('Начать обсуждение?',`<p>${esc(scenarios[current].question)}</p><div class="quote-roster">${selectedModels().map(m=>`<span><img src="${m.image}" alt="" width="20" height="20">${esc(m.name)}</span>`).join('')}</div><div class="balance-rows"><div class="balance-row"><span>Состав</span><strong>${memberCount(selection.length)}</strong></div><div class="balance-row"><span>Проверка</span><strong>1 раунд</strong></div><div class="balance-row"><span>Лимит в примере</span><strong>до ${selection.length} баллов</strong></div></div><p class="modal-note">Просмотр примера бесплатен. Реплики подготовлены заранее и не являются ответами выбранных моделей.</p><div class="modal-actions"><button class="primary-button" data-start="${current}">Начать обсуждение</button><button class="secondary-button" data-close>Отмена</button></div>`);return;}
  if(kind==='auth'){dialogFrame('Добро пожаловать в Council','<p>Выберите форму, чтобы посмотреть вход или регистрацию. Аккаунты пока не создаются.</p><div class="modal-actions"><a class="primary-button" href="signup.html">Создать аккаунт</a><a class="secondary-button" href="login.html">Войти</a></div><p class="modal-note">Вы можете продолжить просмотр примеров без регистрации.</p>');return;}
  if(kind==='models'){dialogFrame('Модели','<div id="modal-picker"></div>');mountPicker($('modal-picker'),{dismiss:true});return;}
  if(kind==='balance'){dialogFrame('Баланс и расходы','<p>Покупайте баллы для разборов, когда они нужны. Без обязательной подписки.</p><div class="balance-number">— <small>баллов</small></div><p>Это пример отображения баланса. Реальных начислений и списаний нет.</p><div class="balance-rows"><div class="balance-row"><span>До запуска</span><strong>Лимит стоимости</strong></div><div class="balance-row"><span>После завершения</span><strong>Фактический расход</strong></div></div><div class="modal-actions"><a class="primary-button" href="balance.html">Открыть баланс</a></div>');return;}
  if(kind==='privacy'){dialogFrame('Ваши данные','<p>Вопрос и контекст хранятся только в этой вкладке браузера. Сохранённые примеры и настройки остаются на этом устройстве. Текст не отправляется AI.</p><div class="modal-box"><h3>Формы входа и регистрации</h3><p>Формы показывают последовательность экранов. Они не отправляют письма, не создают аккаунты и не сохраняют пароли.</p></div><div class="modal-actions"><a class="secondary-button" href="privacy.html">Подробнее</a><button class="quiet-button danger-button" data-clear="true">Удалить локальные данные</button></div>');return;}
  if(kind==='about'){dialogFrame('О Council','<p>Здесь можно выбрать состав, пройти обсуждение, сохранить результат и посмотреть формы.</p><div class="modal-box"><h3>Как устроен этот просмотр</h3><p>Ответы написаны заранее. Вход, письма, AI и оплата не подключены; реальные аккаунты и списания не создаются.</p></div><div class="modal-actions"><a class="secondary-button" href="help.html">Помощь</a><button class="text-button" data-dialog="states">Состояния интерфейса</button></div>');return;}
  if(kind==='custom'){dialogFrame(draftStored?'Ваш вопрос сохранён как черновик':'Ваш вопрос остаётся на экране',`<p>Разбор собственных вопросов пока недоступен. Ваш текст не отправлен. Можно открыть готовый пример.</p>${draftStored?'':'<p class="modal-note">Браузер запретил сохранение. Скопируйте вопрос перед обновлением или закрытием страницы.</p>'}<div class="modal-actions"><button class="primary-button" data-start="mvp">Посмотреть пример</button><button class="secondary-button" data-close>Вернуться к вопросу</button></div>`);return;}
  if(kind==='states'){dialogFrame('Состояния интерфейса','<p>Проверьте, как выглядит продукт в разных ситуациях.</p><div class="state-list"><button data-state="home">Новый вопрос <span>→</span></button><button data-state="run">Разбор в процессе <span>→</span></button><button data-state="result">Готовый результат <span>→</span></button><button data-state="error">Прерванное обсуждение <span>→</span></button><button data-state="insufficient">Недостаточно баллов <span>→</span></button><button data-state="empty-history">Пустая история <span>→</span></button></div>');return;}
  if(kind==='insufficient'){dialogFrame('На этот разбор не хватает баллов','<p>Пример: максимальная стоимость запуска — 5 баллов, на балансе — 2. Разбор не начнётся, пока лимит не будет покрыт.</p><div class="modal-box"><h3>Списаний нет</h3><p>Это пример состояния, а не ваш реальный баланс.</p></div><div class="modal-actions"><a class="primary-button" href="balance.html">Посмотреть пакеты</a><button class="secondary-button" data-close>Закрыть</button></div>');return;}
 }
 async function copy(text){try{if(!navigator.clipboard?.writeText)throw new Error();await navigator.clipboard.writeText(text);toast('Текст скопирован');}catch{const t=document.createElement('textarea');t.value=text;t.style.cssText='position:fixed;top:0;left:-9999px';document.body.append(t);t.select();let ok=false;try{ok=document.execCommand('copy');}catch{}t.remove();toast(ok?'Текст скопирован':'Копирование недоступно в этом браузере. Выделите текст вручную.');}}
 function saveResult(){if(saved.some(v=>v.id===current)){toast('Этот пример уже сохранён в браузере');return;}const next=sanitizeSaved([{id:current,time:Date.now(),modelIds:[...runSelection]},...saved]);if(!storage.set('saved',next)){toast('Браузер не разрешил сохранение');return;}saved=next;$('save-result').textContent='Сохранено';renderSidebar();toast('Пример сохранён на этом устройстве');}
 function clearLocal(){dialogFrame('Удалить локальные данные?','<p>Будут удалены сохранённые примеры, черновик и настройки Council в браузере. Другие данные сайта не изменятся.</p><div class="modal-actions"><button class="secondary-button" data-close>Отмена</button><button class="primary-button" id="confirm-clear">Удалить</button></div>');$('confirm-clear').onclick=()=>{try{['saved','models','versions','motion'].forEach(k=>localStorage.removeItem('council-beta:'+k));sessionStorage.removeItem('council-beta:draft');}catch{toast('Не удалось очистить хранилище');return;}saved=[];selection=[...defaults];runSelection=[...selection];syncRoster();$('question').value='';$('context').value='';setContextOpen(false);draftStored=true;updateDraftStatus();$('question-error').hidden=true;$('question').removeAttribute('aria-invalid');delete document.body.dataset.reducedMotion;renderSidebar();closeDialog();if(view==='page')renderPage();toast('Локальные данные удалены');};}
 $('question-form').addEventListener('submit',async e=>{e.preventDefault();const q=$('question').value.trim();if(!q){$('question-error').textContent='Опишите вопрос или выберите пример ниже.';$('question-error').hidden=false;$('question').setAttribute('aria-invalid','true');$('question').focus();return;}$('question-error').hidden=true;$('question').removeAttribute('aria-invalid');setDraft();
 if(CouncilActions.connected('discussion.create')){
  const button=$('start-button');button.disabled=true;button.setAttribute('aria-busy','true');
  try{await CouncilActions.run('discussion.create',{question:q,context:$('context').value.trim(),modelIds:[...selection],rounds:1});}
  catch{$('question-error').textContent='Не удалось начать обсуждение. Попробуйте ещё раз.';$('question-error').hidden=false;}
  finally{button.disabled=false;button.removeAttribute('aria-busy');}
  return;
 }
 const id=matchScenario(q,$('context').value);if(id)start(id);else showDialog('custom');});
 for(const id of ['question','context'])$(id).addEventListener('input',()=>{setDraft();$('question-error').hidden=true;$('question').removeAttribute('aria-invalid');});
 $('context-toggle').onclick=()=>{const open=$('context-fields').hidden;setContextOpen(open);if(open)$('context').focus();};
 $('skip-demo').onclick=()=>showResult();$('stop-demo').onclick=()=>{setView('home');toast('Показ остановлен. Списаний нет.');};$('retry-demo').onclick=()=>start();$('copy-result').onclick=()=>copy(textResult(current));$('save-result').onclick=saveResult;$('revise-question').onclick=()=>prefill(current);
 for(const key of ['summary','discussion']){$(key+'-tab').onclick=()=>activateTab(key);$(key+'-tab').addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'summary':e.key==='End'?'discussion':key==='summary'?'discussion':'summary';activateTab(next,true);}});}
 $('open-menu').onclick=()=>{$('sidebar').classList.add('open');$('scrim').hidden=false;$('open-menu').setAttribute('aria-expanded','true');document.body.classList.add('menu-open');document.querySelector('.app-shell').inert=true;$('close-menu').focus();};$('close-menu').onclick=()=>{closeMenu();$('open-menu').focus();};$('scrim').onclick=closeMenu;
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.open){const wasOpen=$('sidebar').classList.contains('open');closeMenu();if(wasOpen)$('open-menu').focus();}if(e.key==='Tab'&&$('sidebar').classList.contains('open')&&!modal.open){const all=[...$('sidebar').querySelectorAll('a[href],button:not([disabled])')].filter(n=>n.offsetParent!==null);const first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}if((e.metaKey||e.ctrlKey)&&e.key==='Enter'&&view==='home'&&!modal.open){e.preventDefault();$('question-form').requestSubmit();}});
 matchMedia('(min-width:801px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
 document.addEventListener('click',e=>{
  const target=e.target.closest('button,a');if(!target)return;
  if(target.dataset.dialog){e.preventDefault();showDialog(target.dataset.dialog);}
  if(target.hasAttribute('data-close'))closeDialog();
  if(target.dataset.action==='new')newDiscussion();
  if(target.dataset.action==='return')returnToQuestion();
  if(target.dataset.prefill)prefill(target.dataset.prefill);
  if(target.dataset.result)showResult(target.dataset.result,target.dataset.team?target.dataset.team.split(','):selection);
  if(target.dataset.start){closeDialog();start(target.dataset.start);}
  if(target.dataset.clear)clearLocal();
  if(target.dataset.state){const state=target.dataset.state;closeDialog();if(state==='insufficient')showDialog('insufficient');else if(state==='run')start('mvp');else if(state==='result')showResult('mvp');else if(state==='empty-history'){location.href='history.html?empty=1';}else setView(state);}
 });
 function heading(title,description){return `<div class="page-heading"><h1>${esc(title)}</h1><p>${esc(description)}</p></div>`;}
 function renderPage(){
  const page=document.body.dataset.page;if(!page)return;const root=$('page-view');setView('page',{focus:false});
  if(page==='models'){
   root.innerHTML=heading('Модели','Выберите участников для вашего вопроса.')+'<div id="page-model-picker"></div>';
   mountPicker($('page-model-picker'));
  }
 if(page==='history'){
   const empty=new URLSearchParams(location.search).has('empty');const rows=empty?[]:saved;
   root.innerHTML=heading('История','Сохранённые обсуждения на этом устройстве.')+`<label class="search-field"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4.5 4.5"/></svg><input id="history-search" type="search" placeholder="Найти обсуждение" aria-label="Поиск в истории"></label><div id="history-list"></div>`;
   function list(query=''){const filtered=rows.filter(v=>scenarios[v.id].question.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru')));$('history-list').innerHTML=filtered.length?filtered.map(v=>`<article class="history-item"><button data-result="${v.id}" data-team="${v.modelIds.join(',')}"><span class="history-date">Пример · ${new Date(v.time).toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</span><strong>${esc(scenarios[v.id].question)}</strong><span class="history-meta">${memberCount(v.modelIds.length)} · готовый результат</span></button><button class="icon-button" data-remove="${v.id}" aria-label="Удалить сохранённый пример ${esc(scenarios[v.id].nav)}">×</button></article>`).join(''):`<div class="empty-state"><span aria-hidden="true">${query?'⌕':'↗'}</span><h2>${query?'Ничего не найдено':'Пока нет сохранённых обсуждений'}</h2><p>${query?'Попробуйте другое слово.':'Откройте подготовленный пример и нажмите «Сохранить» у результата.'}</p>${query?'':'<button class="secondary-button" data-result="mvp">Посмотреть пример</button>'}</div>`;root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const id=b.dataset.remove;dialogFrame('Удалить сохранённый пример?','<p>Пример исчезнет из вашей локальной истории. Его можно будет открыть заново под полем вопроса.</p><div class="modal-actions"><button class="secondary-button" data-close>Отмена</button><button class="primary-button" id="delete-saved">Удалить</button></div>');$('delete-saved').onclick=()=>{const next=saved.filter(x=>x.id!==id);if(!storage.set('saved',next)){toast('Не удалось сохранить изменение');return;}saved=next;closeDialog();renderSidebar();renderPage();toast('Пример удалён из истории');};});}
   list();$('history-search').oninput=e=>list(e.target.value);
  }
  if(page==='balance'){
   root.innerHTML=heading('Баланс','Разовые пакеты баллов. Без подписки.')+`<div class="wallet-summary"><div><span>Ваш баланс</span><strong>— <small>баллов</small></strong></div><a class="text-button" href="login.html">Войти</a></div><div class="pack-grid">${packs.map(p=>`<article class="pack-card"><p>${p.name}</p><h2>${p.amount} <small>баллов</small></h2><strong>${p.price.toLocaleString('ru-RU')} ₽</strong><span>Предварительная цена</span><a class="${p.id==='regular'?'primary-button':'secondary-button'}" href="checkout.html?pack=${p.id}">Выбрать пакет</a></article>`).join('')}</div><div class="billing-note"><h2>Стоимость видна заранее</h2><p>Перед обсуждением вы увидите максимальный расход. Расход будет зависеть от объёма задачи и состава. Покупка баллов пока недоступна.</p></div><section class="transactions"><h2>История операций</h2><div class="empty-state compact"><p>Операций пока нет.</p></div></section>`;
  }
  if(page==='settings'){
   const reduce=storage.get('motion',false)===true;
   root.innerHTML=heading('Настройки','Отображение и данные на этом устройстве.')+`<section class="settings-section"><h2>Отображение</h2><label class="setting-row"><span><strong>Минимум движения</strong><small>Отключить короткие переходы и индикатор вращения.</small></span><input class="switch" type="checkbox" id="motion-setting" role="switch" ${reduce?'checked':''}></label><div class="setting-row"><span><strong>Язык интерфейса</strong><small>Первая бета для русскоязычных пользователей.</small></span><span class="tag">Русский</span></div></section><section class="settings-section"><h2>Аккаунт</h2><div class="setting-row"><span><strong>Гостевой просмотр</strong><small>Формы входа и регистрации.</small></span><a class="secondary-button" href="login.html">Войти</a></div></section><section class="settings-section"><h2>Данные на устройстве</h2><div class="setting-row"><span><strong>Сохранённые обсуждения и черновик</strong><small>Черновик — в текущей вкладке. Примеры и настройки — в этом браузере.</small></span><button class="quiet-button danger-button" data-clear="true">Удалить</button></div></section>`;
   $('motion-setting').onchange=e=>{if(storage.set('motion',e.target.checked)){document.body.dataset.reducedMotion=String(e.target.checked);toast('Настройка сохранена');}else toast('Браузер не разрешил сохранение');};
  }
  if(page==='help'){
   root.innerHTML=heading('Помощь','Ответы на вопросы о Council.')+`<div class="help-list">${[['Что делает Council?','Помогает сопоставить независимые позиции по одной задаче, проверить возражение и получить короткий итог. Этот путь можно посмотреть на готовых примерах.'],['Здесь уже отвечают настоящие нейросети?','Сейчас доступны готовые примеры с заранее написанными репликами. Собственные вопросы не отправляются в AI.'],['Как запустить собственный вопрос?','Вы можете набрать его и сохранить как черновик в текущей вкладке. Настоящий разбор станет доступен после подключения и проверки AI. Сейчас кнопка предложит посмотреть подготовленный пример.'],['Совет гарантирует правильный ответ?','Нет. Совпадающие ответы могут содержать общую ошибку. Полезный итог должен показывать основания, ограничения и вопросы, которые ещё нужно проверить.'],['Что означают баллы?','Это единицы бюджета Council, а не сырые API-токены. Расход будет показываться до платного запуска. Подготовленные примеры бесплатны.'],['Что происходит с моими данными?','Вопросы не отправляются в AI. Черновик остаётся в текущей вкладке, а сохранённые примеры и настройки — в этом браузере. Формы не создают настоящие аккаунты.']].map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">＋</span></summary><p>${a}</p></details>`).join('')}</div><div class="support-box"><h2>Есть замечание по интерфейсу?</h2><p>В форме обратной связи можно подготовить сообщение. Отправка появится при подключении сервиса поддержки.</p><a class="secondary-button" href="support.html">Открыть форму</a></div>`;
  }
 }
 if(storage.get('motion',false)===true)document.body.dataset.reducedMotion='true';
 restoreDraft();renderSidebar();syncRoster();
 if(document.body.dataset.page)renderPage();else{const params=new URLSearchParams(location.search);if(Object.hasOwn(scenarios,params.get('example')))showResult(params.get('example'),params.has('team')?params.get('team').split(','):selection);else if(Object.hasOwn(scenarios,params.get('preset')))prefill(params.get('preset'));else setView('home',{focus:false});}
 window.addEventListener('pagehide',cancelRun);
 globalThis.CouncilBetaUI=Object.freeze({showResult,start,setView});
})();
