(() => {
 'use strict';
 const U=CouncilUI,I=CouncilI18n,E=CouncilExamples,{t,esc,icon}=U,root=document.getElementById('workspace-root');
 const initial=U.read('draft-v2',{},true),page=document.body.dataset.page||'beta';
 const state={page,q:typeof initial.q==='string'?initial.q.slice(0,100000):'',context:typeof initial.context==='string'?initial.context.slice(0,50000):'',contextOpen:Boolean(initial.context),web:initial.web!==false,modelIds:CouncilConfig.normalizeSelection(U.read('selection',CouncilConfig.defaults)),modelVersions:CouncilConfig.normalizeVersions(U.read('model-versions',{})),files:[],thread:null,busy:false,search:'',cloud:[],cloudLoaded:false};
 let pending=null,timer=null,saveTimer=null,readingCount=0,runVersion=0;
 const phases=['phasePositions','phaseResearch','phaseDebate','phaseQuestions','phaseResult'];
 const uid=()=>globalThis.crypto?.randomUUID?.()||'c'+Date.now()+Math.random().toString(16).slice(2);
 function localHistory(){const raw=U.read('threads-v2',[]);return Array.isArray(raw)?raw.filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string'&&Number.isFinite(x.time)&&Number.isFinite(new Date(x.time).getTime())&&['example','draft','live'].includes(x.kind)).slice(0,60):[];}
 function historyEntries(){return [...state.cloud,...localHistory()].sort((a,b)=>b.time-a.time);}
 function storeThread(){const th=state.thread;if(!th)return;const remember=U.read('remember-text',false)===true;if(th.kind!=='example'&&!remember)return;
  const record={id:th.id,kind:th.kind,scenarioId:th.scenarioId||null,title:th.kind==='example'&&!th.customTitle?'':String(th.title||th.q).slice(0,180),time:th.time,modelIds:[...state.modelIds],modelVersions:{...state.modelVersions},customTitle:!!th.customTitle};
  if(th.kind==='example'){record.title=record.title||E.get(th.scenarioId).question;record.finished=th.turns.some(x=>x.example&&x.phase===4);if(remember){record.answers=th.turns.find(x=>x.example)?.answers||[];record.prompt=th.turns.find(x=>x.example)?.prompt||'';}}
  else{record.thread={...th,turns:th.turns.map(({request,files,...turn})=>turn)};}
  const items=localHistory().filter(x=>x.id!==record.id);items.unshift(record);const saved=U.write('threads-v2',items.slice(0,60));renderSidebar();return saved;
 }
 function draft(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>U.write('draft-v2',{q:state.q,context:state.context,web:state.web},true),220);}
 function capture(){const q=document.getElementById('question-input');if(q)state.q=q.value;const c=document.getElementById('context-input');if(c)state.context=c.value;const turn=state.thread?.turns.findLast(x=>x.example);if(turn){document.querySelectorAll('[data-clarification]').forEach(el=>turn.answers[Number(el.dataset.clarification)]=el.value);const prompt=document.getElementById('prompt-editor');if(prompt)turn.prompt=prompt.value;}}
 function newThread(){cancelRun();state.thread=null;state.q='';state.context='';state.contextOpen=false;state.files=[];U.remove('draft-v2',true);if(state.page!=='beta'){location.href='index.html';return;}history.replaceState({},'','index.html');render();document.getElementById('question-input')?.focus();}
 function sidebar(){return `<aside class="sidebar" id="sidebar" aria-label="Council"><div class="brand-row"><a class="wordmark" href="index.html" aria-label="Council">council<span>.</span></a><button class="icon-button" data-toggle-sidebar aria-label="${esc(t('collapse'))}">${icon('panel')}</button></div><button class="side-link" data-new>${icon('plus')}<span>${esc(t('newChat'))}</span></button><a href="history.html" class="side-link" ${page==='history'?'aria-current="page"':''}>${icon('search')}<span>${esc(t('history'))}</span></a><div class="sidebar-history" id="sidebar-history"></div><div class="side-bottom">${[['balance','wallet'],['settings','settings'],['help','help']].map(([id,ic])=>`<a href="${id}.html" class="side-link" ${page===id?'aria-current="page"':''}>${icon(ic)}<span>${esc(t(id))}</span></a>`).join('')}<div data-account-control>${U.sessionLink()}</div></div></aside><button class="sidebar-scrim" aria-label="${esc(t('close'))}" data-toggle-sidebar></button>`;}
 function entryTitle(item){return item.kind==='example'&&!item.customTitle&&E.get(item.scenarioId)?E.get(item.scenarioId).question:item.title;}
 function renderSidebar(){const el=document.getElementById('sidebar-history');if(!el)return;const items=historyEntries();let lastGroup='';el.innerHTML=`<details id="recent-details" ${U.read('history-open',true)!==false?'open':''}><summary>${esc(t('recent'))}</summary>${items.length?items.slice(0,35).map(item=>{const group=new Date(item.time).toDateString()===new Date().toDateString()?'today':'earlier';const heading=group!==lastGroup?`<p class="history-group-title">${esc(t(group))}</p>`:'';lastGroup=group;return `${heading}<div class="history-item ${state.thread?.id===item.id?'active':''}"><a href="index.html?thread=${encodeURIComponent(item.id)}" data-open-thread="${esc(item.id)}" title="${esc(entryTitle(item))}">${esc(entryTitle(item))}</a><button class="icon-button" data-thread-menu="${esc(item.id)}" aria-label="${esc(t('edit'))}">${icon('more')}</button></div>`;}).join(''):`<p class="sidebar-empty">${esc(t('historyEmpty'))}</p>`}</details>`;el.querySelector('details').ontoggle=e=>U.write('history-open',e.currentTarget.open);el.querySelectorAll('[data-thread-menu]').forEach(b=>b.onclick=()=>threadMenu(b.dataset.threadMenu));el.querySelectorAll('[data-open-thread]').forEach(a=>a.onclick=e=>{if(state.page==='beta'){e.preventDefault();openThread(a.dataset.openThread);}});}
 function render(){const scroll=document.getElementById('app-content')?.scrollTop||0;document.title=(state.thread?state.thread.title||state.thread.q:t(page==='beta'?'newChat':page))+' — Council';const label=page==='beta'?'Council':t(page);root.innerHTML=sidebar()+`<div class="app-shell"><header class="topbar"><div class="topbar-left"><button class="icon-button sidebar-open-button" data-toggle-sidebar aria-label="${esc(t('expand'))}">${icon('panel')}</button><span class="page-label">${esc(label)}</span></div>${U.languages()}</header><main class="app-main" id="app-content" tabindex="-1"></main><div id="composer-bottom"></div><footer class="app-fineprint"><a href="privacy.html">${esc(t('privacy'))}</a> · <a href="terms.html">${esc(t('terms'))}</a></footer></div>`;
  root.querySelectorAll('[data-toggle-sidebar]').forEach(b=>b.onclick=toggleSidebar);root.querySelector('[data-new]').onclick=newThread;renderSidebar();const main=document.getElementById('app-content');if(page==='beta')renderChat(main);else renderPage(main);main.scrollTop=scroll;root.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;},{once:true}));
 }
 function toggleSidebar(){if(matchMedia('(max-width:850px)').matches){document.body.classList.toggle('sidebar-mobile-open');}else{document.body.classList.toggle('sidebar-collapsed');U.write('sidebar-collapsed',document.body.classList.contains('sidebar-collapsed'));}root.querySelectorAll('[data-toggle-sidebar]').forEach(b=>b.setAttribute('aria-expanded',String(matchMedia('(max-width:850px)').matches?document.body.classList.contains('sidebar-mobile-open'):!document.body.classList.contains('sidebar-collapsed'))));}
 function saveModels(ids,versions){state.modelIds=[...ids];state.modelVersions={...versions};U.write('selection',ids);U.write('model-versions',versions);if(state.thread)storeThread();}
 function roster(){return `<span class="model-marks">${state.modelIds.map(U.modelMark).join('')}</span><span>${state.modelIds.length===1?esc(CouncilConfig.getVariant(state.modelIds[0],state.modelVersions[state.modelIds[0]]).name):esc(t('models'))+' · '+state.modelIds.length}</span><span aria-hidden="true">⌄</span>`;}
 function composer(){const inChat=!!state.thread;return `<form class="composer" id="question-form"><div class="file-tray" id="file-tray" ${state.files.length?'':'hidden'}></div><label class="sr-only" for="question-input">${esc(t('question'))}</label><textarea id="question-input" maxlength="100000" rows="${inChat?2:3}" placeholder="${esc(t(inChat?'followupPlaceholder':'questionPlaceholder'))}" ${state.busy?'disabled':''}>${esc(state.q)}</textarea><div class="context-field" id="context-field" ${state.contextOpen?'':'hidden'}><label for="context-input">${esc(t('contextLabel'))}</label><textarea id="context-input" rows="3" maxlength="50000" placeholder="${esc(t('contextPlaceholder'))}">${esc(state.context)}</textarea></div><p class="form-error" id="question-error" role="alert" hidden></p><div class="composer-controls"><div class="composer-options"><button type="button" class="icon-button" id="attach-button" title="${esc(t('attach'))}" aria-label="${esc(t('attach'))}">${icon('attach')}</button><input type="file" id="file-input" accept=".txt,.md,.csv,.json,.pdf,.docx" multiple hidden><button type="button" class="model-picker-button" id="choose-models" aria-haspopup="dialog">${roster()}</button><button type="button" id="web-toggle" class="web-toggle" aria-pressed="${state.web}" title="${esc(t('web'))}" aria-label="${esc(t('web'))}">${icon('globe')}<span>${esc(t('web'))}</span></button><button type="button" class="icon-button" id="context-toggle" aria-label="${esc(t('context'))}" title="${esc(t('context'))}" aria-expanded="${state.contextOpen}" aria-controls="context-field">${icon('edit')}</button></div>${state.busy?`<button class="composer-send" type="button" id="stop-run" aria-label="${esc(t('stop'))}">${icon('stop')}</button>`:`<button class="composer-send" type="submit"><span>${esc(t(inChat?'send':'discuss'))}</span>${icon('arrow')}</button>`}</div></form><div class="composer-hint" id="draft-status">${state.files.length?esc(t('filesHint')):''}</div>`;}
 function renderChat(main){if(!state.thread){main.innerHTML=`<section class="workspace-home product-entry"><h1 class="entry-title"><span>${esc(t('entryTitleStart'))}</span> <span class="entry-emphasis">${esc(t('entryTitleEnd'))}</span></h1>${composer()}</section>`;}else{main.innerHTML=`<div class="conversation" id="conversation">${state.thread.turns.map((turn,index)=>renderTurn(turn,index)).join('')}</div>`;document.getElementById('composer-bottom').className='conversation-composer';document.getElementById('composer-bottom').innerHTML=`<div>${composer()}</div>`;bindConversation();}bindComposer();}
 function renderTurn(turn,index){if(turn.role==='user')return `<article class="user-message">${esc(turn.text)}${turn.context?`<details><summary>${esc(t('contextLabel'))}</summary>${esc(turn.context)}</details>`:''}${turn.fileNames?.length?`<div class="file-meta">${icon('file')}${esc(t('submittedFiles',{n:turn.fileNames.length}))}</div>`:''}</article>`;
  const rosterNote=!turn.example&&turn.models?.length?`<details class="turn-models"><summary>${esc(t('modelRoster'))} · ${turn.models.length}</summary><p>${turn.models.map(m=>esc(CouncilConfig.getVariant(m.familyId,m.modelId)?.name||m.modelId)).join(' · ')}</p></details>`:'';
  const label=`<div class="assistant-label"><span class="council-glyph" aria-hidden="true">✳</span>Council ${turn.example?`<span class="example-label" title="${esc(t('exampleNote'))}">${esc(t('example'))}</span>`:''}<button class="icon-button" data-public-info aria-label="${esc(t('publicNotesInfo'))}" title="${esc(t('publicNotes'))}">${icon('help')}</button></div>${rosterNote}`;
  if(turn.error)return `<article class="assistant-block">${label}<div class="conversation-error"><h3>${esc(t(turn.error==='INTEGRATION_REQUIRED'?'unavailable':'requestFailed'))}</h3><p>${esc(t(turn.error==='INTEGRATION_REQUIRED'?'unavailableBody':'networkError'))}</p><button class="button subtle" data-retry="${index}">${icon('message')}${esc(t('retry'))}</button></div></article>`;
  if(turn.paused)return `<article class="assistant-block">${label}<p class="muted prose">${esc(t('paused'))}</p><button class="button subtle" data-resume="${index}">${esc(t('resume'))}</button></article>`;
  if(turn.example){const s=E.get(turn.scenarioId);const count=turn.modelIds.length;let stages='';if(turn.phase>=0)stages+=phaseHtml(0,`<div>${s.positions.slice(0,count).map((p,i)=>`<div class="position-item"><h3>${esc(t('position',{n:i+1}))}</h3><p>${esc(p)}</p></div>`).join('')}</div>`,turn.phase===0);if(turn.phase>=1)stages+=phaseHtml(1,`<p class="small-note">${esc(t('researchEmpty'))}</p><ul class="evidence-list">${s.checks.map(c=>`<li>${esc(c)}</li>`).join('')}</ul>`,turn.phase===1);if(turn.phase>=2&&count>1)stages+=phaseHtml(2,`<p class="prose">${esc(s.review)}</p>`,turn.phase===2);
   let body=`<div class="phase-list">${stages}</div>${count===1?`<p class="small-note">${esc(t('singleNote'))}</p>`:''}`;if(turn.phase===3){body+=`<form class="questions-form" data-questions="${index}"><h2>${esc(t('phaseQuestions'))}</h2><p class="muted prose">${esc(t('questionIntro'))}</p>${s.questions.map((q,i)=>`<div class="field"><label for="clarify-${index}-${i}">${i+1}. ${esc(q)}</label><textarea id="clarify-${index}-${i}" data-clarification="${i}" maxlength="4000" rows="2">${esc(turn.answers?.[i]||'')}</textarea></div>`).join('')}<div class="question-actions"><button class="button dark" type="submit">${esc(t('makePrompt'))}</button><button type="button" class="button subtle" data-skip="${index}">${esc(t('skipQuestions'))}</button></div></form>`;}if(turn.phase===4)body+=`<div class="result-brief"><h2>${esc(t('conclusion'))}</h2><p class="prose">${esc(s.result)}</p><div class="result-open"><h3>${esc(t('openQuestions'))}</h3><p class="prose">${esc(s.uncertainty)}</p></div></div>${promptHtml(turn,index)}<div class="result-tools"><button class="button subtle" data-save-thread>${icon('check')}${esc(t('save'))}</button><button class="button subtle" data-export-thread>${icon('download')}${esc(t('download'))}</button></div>`;
   if(turn.phase<3)body+=`<div class="waiting-row"><span class="waiting-dot"></span>${esc(t(phases[Math.min(turn.phase+1,3)]))}</div>`;return `<article class="assistant-block">${label}${body}</article>`;
  }
  const events=(turn.events||[]).map(event=>{if(event.type==='source'){const url=U.safeUrl(event.url);return url?`<a class="source-card" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(event.title||t('source'))}<small>${esc(new URL(url).hostname)}</small></a>`:'';}return `<div class="position-item"><h3>${esc(event.title||t({position:'phasePositions',review:'phaseDebate',question:'phaseQuestions'}[event.type]||'publicNotes'))}</h3><p>${esc(event.text||'')}</p></div>`;}).join('');return `<article class="assistant-block">${label}${events?`<details class="phase" open><summary>${esc(t('publicNotes'))}</summary><div class="phase-content">${events}</div></details>`:''}${turn.text?`<p class="prose" style="white-space:pre-wrap">${esc(turn.text)}</p>`:''}${turn.prompt?promptHtml(turn,index):''}${turn.questions?.length?liveQuestions(turn,index):''}${state.busy&&index===state.thread.turns.length-1?`<div class="waiting-row"><span class="waiting-dot"></span>${esc(t('preparing'))}</div>`:''}</article>`;
 }
 function phaseHtml(index,body,current){return `<details class="phase ${current?'current':'complete'}" ${current?'open':''}><summary>${esc(t(phases[index]))}</summary><div class="phase-content">${body}</div></details>`;}
 function promptHtml(turn,index){const prompt=turn.prompt||E.prompt(turn.scenarioId,turn.answers);return `<section class="prompt-card"><div class="prompt-card-head"><h3>${esc(t('finalPrompt'))}</h3><div class="prompt-card-actions"><button class="icon-button" data-edit-prompt="${index}" aria-label="${esc(t('edit'))}">${icon('edit')}</button><button class="icon-button" data-copy-prompt="${index}" aria-label="${esc(t('copy'))}">${icon('copy')}</button><button class="icon-button" data-download-prompt="${index}" aria-label="${esc(t('download'))}">${icon('download')}</button></div></div>${turn.editing?`<textarea class="prompt-editor" id="prompt-editor" aria-label="${esc(t('finalPrompt'))}" maxlength="100000">${esc(prompt)}</textarea>`:`<pre class="prompt-text">${esc(prompt)}</pre>`}</section><p class="small-note" style="margin-top:12px">${esc(t('promptNote'))}</p>`;}
 function bindComposer(){const form=document.getElementById('question-form');if(!form)return;const q=form.querySelector('#question-input'),c=form.querySelector('#context-input');q.oninput=()=>{state.q=q.value;draft();q.style.height='auto';q.style.height=Math.min(q.scrollHeight,state.thread?140:260)+'px';};q.onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'&&!e.isComposing){e.preventDefault();form.requestSubmit();}};c.oninput=()=>{state.context=c.value;draft();};form.onsubmit=e=>{e.preventDefault();capture();submit();};form.querySelector('#choose-models').onclick=()=>U.modelPicker(state.modelIds,(ids,versions)=>{saveModels(ids,versions);document.getElementById('choose-models').innerHTML=roster();},state.modelVersions);form.querySelector('#context-toggle').onclick=e=>{state.contextOpen=!state.contextOpen;form.querySelector('#context-field').hidden=!state.contextOpen;e.currentTarget.setAttribute('aria-expanded',String(state.contextOpen));if(state.contextOpen)c.focus();};form.querySelector('#web-toggle').onclick=e=>{state.web=!state.web;e.currentTarget.setAttribute('aria-pressed',String(state.web));draft();};form.querySelector('#attach-button').onclick=()=>form.querySelector('#file-input').click();form.querySelector('#file-input').onchange=e=>{readFiles([...e.target.files]);e.target.value='';};form.querySelector('#stop-run')?.addEventListener('click',()=>{const turn=state.thread?.turns.at(-1);cancelRun();if(turn)turn.paused=true;render();});form.ondragover=e=>{e.preventDefault();form.classList.add('dragging');};form.ondragleave=()=>form.classList.remove('dragging');form.ondrop=e=>{e.preventDefault();form.classList.remove('dragging');readFiles([...e.dataTransfer.files]);};renderFiles();}
 async function readFiles(files){if(state.files.length+files.length>8){U.toast(t('filesMany'));return;}for(const file of files){const item={id:uid(),name:file.name,loading:true};state.files.push(item);readingCount++;renderFiles();try{const parsed=await CouncilFiles.read(file);if(state.files.filter(x=>x.id!==item.id).reduce((n,x)=>n+(x.chars||0),0)+parsed.chars>CouncilFiles.MAX_CHARS)throw Object.assign(new Error(),{code:'filesTextLarge'});Object.assign(item,parsed,{id:item.id,loading:false});}catch(error){item.loading=false;item.error=error.code||'fileReadError';}finally{readingCount--;renderFiles();}}}
 function renderFiles(){const el=document.getElementById('file-tray');if(!el)return;el.hidden=!state.files.length;el.innerHTML=state.files.map(f=>`<div class="file-pill ${f.error?'error':''}">${icon('file')}<button type="button" class="file-info" data-preview-file="${esc(f.id)}" style="border:0;background:none;text-align:left;padding:0" title="${esc(f.error?t(f.error):t('previewFile'))}"><strong>${esc(f.name)}</strong><small>${esc(f.loading?t('reading'):f.error?t(f.error):t('chars',{n:U.format(f.chars)}))}</small></button><button type="button" class="icon-button" data-remove-file="${esc(f.id)}" aria-label="${esc(t('removeFile'))}">${icon('close')}</button></div>`).join('');el.querySelectorAll('[data-remove-file]').forEach(b=>b.onclick=()=>{state.files=state.files.filter(x=>x.id!==b.dataset.removeFile);renderFiles();});el.querySelectorAll('[data-preview-file]').forEach(b=>b.onclick=()=>{const f=state.files.find(x=>x.id===b.dataset.previewFile);if(f.loading)return;if(f.error){U.notice(f.name,t(f.error));return;}U.dialog(f.name,`<p class="small-note">${esc(t('filesEphemeral'))}</p><pre class="file-text">${esc(f.text)}</pre>`,{wide:true});});const hint=document.getElementById('draft-status');if(hint)hint.textContent=state.files.length?t('filesHint'):'';}
 function prefill(id){const scenario=E.get(id);if(!scenario)return;capture();if(state.q.trim()&&!E.match(state.q,state.context)){U.dialog(t('examples'),`<p class="muted prose">${esc(t('question'))}: ${esc(state.q.slice(0,200))}</p><div class="dialog-actions"><button class="button subtle" data-keep>${esc(t('cancel'))}</button><button class="button dark" data-replace>${esc(t('continue'))}</button></div>`,{onOpen:d=>{d.querySelector('[data-keep]').onclick=U.closeDialog;d.querySelector('[data-replace]').onclick=()=>{U.closeDialog();apply();};}});return;}apply();function apply(){state.q=scenario.question;state.context=scenario.context;state.contextOpen=true;draft();render();document.getElementById('question-input')?.focus();}}
 async function submit(retryIndex=null){if(state.busy)return;if(readingCount){U.toast(t('reading'));return;}if(state.files.some(x=>x.error)){U.toast(t('fileReadError'));return;}if(!state.q.trim()){document.getElementById('question-input')?.focus();return;}if(state.q.length>100000){U.toast(t('inputTooLong'));return;}
  const question=state.q.trim(),context=state.context.trim(),files=state.files.map(f=>({name:f.name,type:f.type,text:f.text})),isNew=!state.thread;const scenarioId=isNew&&!files.length?E.match(question,context):null;
  if(isNew){state.thread={id:uid(),kind:scenarioId?'example':'draft',scenarioId,q:question,context,title:question.slice(0,180),time:Date.now(),turns:[]};history.replaceState({},'','index.html?thread='+encodeURIComponent(state.thread.id));}
  const modelVersions={...state.modelVersions},models=CouncilConfig.selectionDetails(state.modelIds,modelVersions);
  const th=state.thread;th.turns.push({role:'user',text:question,context,fileNames:files.map(f=>f.name),modelIds:[...state.modelIds],modelVersions,models});state.q='';state.context='';state.contextOpen=false;state.files=[];draft();
  if(scenarioId){const turn={role:'assistant',example:true,scenarioId,modelIds:[...state.modelIds],modelVersions,phase:0,answers:[],prompt:''};th.turns.push(turn);state.busy=true;storeThread();render();progressExample(turn);return;}
  const turn={role:'assistant',modelIds:[...state.modelIds],modelVersions,models,events:[],request:{question,context,modelIds:[...state.modelIds],models,catalogDate:CouncilConfig.catalogDate,web:state.web,files}};th.turns.push(turn);state.busy=true;render();await requestAnswer(turn,isNew);
 }
 async function requestAnswer(turn,isNew){if(!turn.request){const previous=state.thread.turns[state.thread.turns.indexOf(turn)-1];if(previous?.fileNames?.length){U.notice(t('material'),t('filesEphemeral'));return;}if(!CouncilConfig.validVersions(turn.modelIds,turn.modelVersions)){U.notice(t('models'),t('modelVersionRequired'));return;}turn.request={question:previous?.text||'',context:previous?.context||'',modelIds:[...turn.modelIds],models:CouncilConfig.selectionDetails(turn.modelIds,turn.modelVersions),catalogDate:CouncilConfig.catalogDate,web:state.web,files:[]};}const action=isNew?'discussion.create':'discussion.reply';const index=state.thread.turns.indexOf(turn);if(!CouncilActions.connected(action)){turn.error='INTEGRATION_REQUIRED';state.busy=false;storeThread();render();scrollBottom();return;}
  const token=++runVersion;const controller=new AbortController();pending=controller;state.busy=true;turn.error=null;turn.paused=false;render();
  try{const request={...turn.request,threadId:state.thread.serverId||null,language:I.lang,previousPrompt:state.thread.turns.findLast(x=>x.prompt)?.prompt||null};const result=await CouncilActions.run(action,request,{signal:controller.signal,onEvent:event=>{if(token!==runVersion||!event||typeof event.type!=='string')return;if(['position','review','question','source'].includes(event.type)){turn.events.push({type:event.type,text:String(event.text||'').slice(0,24000),title:String(event.title||'').slice(0,180),url:U.safeUrl(event.url)});render();}if(event.type==='summary'){turn.text=String(event.text||'').slice(0,100000);render();}if(event.type==='prompt'){turn.prompt=String(event.text||'').slice(0,100000);render();}}});if(token!==runVersion)return;if(!result||(!result.text&&!result.prompt&&!turn.text&&!turn.prompt&&!result.questions?.length))throw new Error('No result');turn.questions=Array.isArray(result.questions)?result.questions.slice(0,6).map(q=>String(q).slice(0,1000)):[];turn.text=String(result.text||turn.text||'');turn.prompt=String(result.prompt||turn.prompt||'');delete turn.request;state.thread.kind='live';state.thread.serverId=result.threadId||state.thread.serverId;state.thread.time=Date.now();}
  catch(error){if(token!==runVersion)return;if(error.name==='AbortError')turn.paused=true;else turn.error=error.code==='INTEGRATION_REQUIRED'?'INTEGRATION_REQUIRED':'REQUEST_FAILED';}
  finally{if(token===runVersion){state.busy=false;pending=null;storeThread();render();scrollBottom();}}
 }
 function progressExample(turn){clearTimeout(timer);state.busy=true;const next=()=>{if(!state.thread?.turns.includes(turn)||turn.paused)return;turn.phase++;if(turn.modelIds.length===1&&turn.phase===2)turn.phase=3;state.busy=turn.phase<3;render();if(state.busy)timer=setTimeout(next,U.read('motion',false)?30:1300);else storeThread();};timer=setTimeout(next,U.read('motion',false)?30:1400);}
 function cancelRun(){clearTimeout(timer);runVersion++;pending?.abort();pending=null;state.busy=false;}
 function finishExample(turn){capture();turn.phase=4;turn.prompt=E.prompt(turn.scenarioId,turn.answers);state.busy=false;storeThread();render();}
 function liveQuestions(turn,index){return `<form class="questions-form" data-live-questions="${index}"><h2>${esc(t('phaseQuestions'))}</h2>${turn.questions.map((q,i)=>`<div class="field"><label for="live-answer-${index}-${i}">${esc(q)}</label><textarea id="live-answer-${index}-${i}" name="answer-${i}" maxlength="4000" rows="2"></textarea></div>`).join('')}<button class="button dark" type="submit">${esc(t('continue'))}</button></form>`;}
 function bindConversation(){document.querySelectorAll('[data-live-questions]').forEach(form=>form.onsubmit=e=>{e.preventDefault();const turn=state.thread.turns[Number(form.dataset.liveQuestions)];state.q=turn.questions.map((q,i)=>q+'\n'+form.querySelector(`[name="answer-${i}"]`).value).join('\n\n');turn.questions=[];submit();});document.querySelectorAll('[data-public-info]').forEach(b=>b.onclick=()=>U.notice(t('publicNotes'),t('publicNotesInfo')+(state.thread.kind==='example'?' '+t('exampleNote'):'')));document.querySelectorAll('[data-questions]').forEach(f=>{f.oninput=capture;f.onsubmit=e=>{e.preventDefault();finishExample(state.thread.turns[Number(f.dataset.questions)]);};});document.querySelectorAll('[data-skip]').forEach(b=>b.onclick=()=>finishExample(state.thread.turns[Number(b.dataset.skip)]));document.querySelectorAll('[data-copy-prompt]').forEach(b=>b.onclick=()=>{capture();const x=state.thread.turns[Number(b.dataset.copyPrompt)];U.copy(x.prompt||E.prompt(x.scenarioId,x.answers));});document.querySelectorAll('[data-download-prompt]').forEach(b=>b.onclick=()=>{capture();const x=state.thread.turns[Number(b.dataset.downloadPrompt)];U.download('council-prompt.txt',x.prompt||E.prompt(x.scenarioId,x.answers));});document.querySelectorAll('[data-edit-prompt]').forEach(b=>b.onclick=()=>{capture();const x=state.thread.turns[Number(b.dataset.editPrompt)];x.editing=!x.editing;render();if(x.editing)document.getElementById('prompt-editor')?.focus();});document.querySelector('[data-save-thread]')?.addEventListener('click',()=>{if(storeThread())U.toast(t('saved'));});document.querySelector('[data-export-thread]')?.addEventListener('click',()=>U.download('council-discussion.txt',exportThread()));document.querySelectorAll('[data-resume]').forEach(b=>b.onclick=()=>{const x=state.thread.turns[Number(b.dataset.resume)];x.paused=false;if(x.example){progressExample(x);render();}else requestAnswer(x,Number(b.dataset.resume)===1);});document.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>{const x=state.thread.turns[Number(b.dataset.retry)];requestAnswer(x,Number(b.dataset.retry)===1);});document.getElementById('prompt-editor')?.addEventListener('input',e=>{const x=state.thread.turns.findLast(x=>x.editing);if(x){x.prompt=e.target.value;x.customPrompt=true;}});}
 function exportThread(){capture();const th=state.thread;if(!th)return '';return ['Council',th.kind==='example'?t('exampleNote'):'',...th.turns.map(turn=>turn.role==='user'?turn.text+(turn.context?'\n'+turn.context:'')+(turn.models?.length?'\n'+turn.models.map(m=>m.modelId).join(' · '):''):turn.example?[E.get(turn.scenarioId).result,turn.prompt||E.prompt(turn.scenarioId,turn.answers)].join('\n\n'):turn.text||t('unavailable'))].filter(Boolean).join('\n\n');}
 function scrollBottom(){requestAnimationFrame(()=>{const main=document.getElementById('app-content');if(main)main.scrollTop=main.scrollHeight;});}
 async function openThread(id){cancelRun();const item=historyEntries().find(x=>x.id===id);if(!item){U.toast(t('noResults'));return;}if(item.cloud){if(!CouncilActions.connected('history.get')){U.toast(t('endpointMissing'));return;}try{const result=await CouncilActions.run('history.get',{id});if(!result?.thread||!Array.isArray(result.thread.turns))throw new Error();state.thread=result.thread;}catch{U.toast(t('networkError'));return;}}
  else if(item.kind==='example'){const s=E.get(item.scenarioId);if(!s)return;state.thread={id:item.id,kind:'example',scenarioId:item.scenarioId,q:s.question,context:s.context,title:entryTitle(item),customTitle:item.customTitle,time:item.time,turns:[{role:'user',text:s.question,context:s.context},{role:'assistant',example:true,scenarioId:item.scenarioId,modelIds:CouncilConfig.normalizeSelection(item.modelIds),phase:item.finished?4:3,answers:item.answers||[],prompt:item.prompt||''}]};}
  else if(item.thread&&Array.isArray(item.thread.turns)){state.thread=item.thread;}else return;
  state.q='';state.context='';state.files=[];state.modelIds=CouncilConfig.normalizeSelection(item.modelIds);state.modelVersions=CouncilConfig.normalizeVersions(item.modelVersions||state.thread.turns.findLast(x=>x.modelVersions)?.modelVersions);history.replaceState({},'','index.html?thread='+encodeURIComponent(id));document.body.classList.remove('sidebar-mobile-open');render();}
 function threadMenu(id){const item=historyEntries().find(x=>x.id===id);if(!item)return;U.dialog(t('history'),`<div class="field"><label for="rename-thread">${esc(t('threadName'))}</label><input id="rename-thread" maxlength="180" value="${esc(entryTitle(item))}"></div><div class="dialog-actions"><button class="button danger" data-delete-thread>${esc(t('delete'))}</button><button class="button dark" data-rename-thread>${esc(t('save'))}</button></div>`,{onOpen:d=>{d.querySelector('[data-rename-thread]').onclick=async()=>{const title=d.querySelector('input').value.trim();if(!title)return;if(item.cloud){try{const r=await CouncilActions.run('history.rename',{id,title});if(!r?.updated)throw new Error();state.cloud.find(x=>x.id===id).title=title;}catch{U.toast(t('networkError'));return;}}else{const list=localHistory();Object.assign(list.find(x=>x.id===id),{title,customTitle:true});U.write('threads-v2',list);}if(state.thread?.id===id){state.thread.title=title;state.thread.customTitle=true;}U.closeDialog();render();};d.querySelector('[data-delete-thread]').onclick=async()=>{U.closeDialog();if(!await U.confirm(t('delete'),t('deleteThread')))return;if(item.cloud){try{const r=await CouncilActions.run('history.delete',{id});if(!r?.deleted)throw new Error();state.cloud=state.cloud.filter(x=>x.id!==id);}catch{U.toast(t('networkError'));return;}}else U.write('threads-v2',localHistory().filter(x=>x.id!==id));if(state.thread?.id===id)newThread();else render();};}});}
 function pageHeader(title,lead=''){return `<header class="page-heading"><h1>${esc(t(title))}</h1>${lead?`<p>${esc(t(lead))}</p>`:''}</header>`;}
 function renderPage(main){main.innerHTML=`<section class="page-content ${['profile','settings','help','history'].includes(page)?'narrow':''}" id="page-content"></section>`;const el=document.getElementById('page-content');
  if(page==='balance')CouncilPlans.mount(el);
  if(page==='history'){el.innerHTML=pageHeader('history')+`<div class="history-toolbar"><label class="sr-only" for="history-search">${esc(t('search'))}</label><input id="history-search" type="search" placeholder="${esc(t('search'))}" value="${esc(state.search)}"><button class="button subtle" id="export-history">${icon('download')}<span>${esc(t('export'))}</span></button></div><p class="micro muted" style="margin-bottom:18px">${esc(t(CouncilSession.current?'cloudHistory':'deviceOnly'))}</p><div id="history-list"></div>`;renderHistoryList();el.querySelector('#history-search').oninput=e=>{state.search=e.target.value;renderHistoryList();};el.querySelector('#export-history').onclick=()=>U.download('council-history.json',JSON.stringify({exportedAt:new Date().toISOString(),scope:'local-browser',discussions:localHistory()},null,2),'application/json');}
  if(page==='models'){el.innerHTML=pageHeader('modelPickerTitle','modelPickerNote')+`<div class="model-options catalog-grid">${U.modelOptions(state.modelIds,state.modelVersions,'catalog')}</div><p class="form-error" id="catalog-error" role="alert" hidden></p><button class="button dark" id="save-models">${esc(t('save'))}</button><p class="small-note" style="margin-top:24px">${esc(t('modelCatalogNote'))}</p>`;U.bindModelOptions(el,()=>el.querySelector('#catalog-error').hidden=true);el.querySelector('#save-models').onclick=()=>{const {ids,versions}=U.readModelOptions(el);if(!CouncilConfig.validVersions(ids,versions)){el.querySelector('#catalog-error').textContent=t('minOne');el.querySelector('#catalog-error').hidden=false;return;}saveModels(ids,versions);U.toast(t('saved'));};}
  if(page==='settings')renderSettings(el);if(page==='profile')renderProfile(el);if(page==='help'){el.innerHTML=pageHeader('help','helpLead')+`<div class="help-list">${[1,2,3,4].map(i=>`<details><summary>${esc(t('faq'+i))}</summary><p>${esc(t('faq'+i+'a'))}</p></details>`).join('')}<details><summary>${esc(t('material'))}</summary><p>${esc(t('filesHint'))}</p><p>${esc(t('filesEphemeral'))}</p></details><details><summary>${esc(t('publicNotes'))}</summary><p>${esc(t('publicNotesInfo'))}</p></details></div><section class="help-examples"><h2 class="section-title">${esc(t('examples'))}</h2><div class="help-example-links">${[['mvp','caseMvp'],['pricing','casePricing'],['launch','caseLaunch']].map(([id,key])=>`<a href="index.html?preset=${id}">${esc(t(key))}<span aria-hidden="true">↗</span></a>`).join('')}</div></section><div class="question-actions"><a class="button dark" href="support.html">${esc(t('support'))}</a><a class="button subtle" href="privacy.html">${esc(t('privacy'))}</a></div>`;}
 }
 function renderHistoryList(){const el=document.getElementById('history-list');const items=historyEntries().filter(x=>entryTitle(x).toLocaleLowerCase().includes(state.search.toLocaleLowerCase()));el.innerHTML=items.length?`<div class="history-list">${items.map(x=>`<div class="history-row"><a href="index.html?thread=${encodeURIComponent(x.id)}"><h2>${esc(entryTitle(x))}</h2><p>${new Intl.DateTimeFormat(I.locale,{dateStyle:'medium',timeStyle:'short'}).format(x.time)} · ${esc(t(x.cloud?'cloudHistory':'deviceOnly'))}</p></a><button class="icon-button" data-thread-menu="${esc(x.id)}" aria-label="${esc(t('edit'))}">${icon('more')}</button></div>`).join('')}</div>`:`<div class="empty-state">${icon('message')}<h2>${esc(t(state.search?'noResults':'historyEmpty'))}</h2><p>${esc(t('historyHint'))}</p><a class="button dark" href="index.html">${esc(t('newChat'))}</a></div>`;el.querySelectorAll('[data-thread-menu]').forEach(b=>b.onclick=()=>threadMenu(b.dataset.threadMenu));}
 function renderSettings(el){el.innerHTML=pageHeader('settings')+`<nav class="account-pages"><a class="active" href="settings.html">${esc(t('general'))}</a><a href="profile.html">${esc(t('account'))}</a></nav><section class="settings-section"><h2>${esc(t('general'))}</h2><div class="setting-row"><div><strong>${esc(t('language'))}</strong></div>${U.languages()}</div><label class="setting-row"><div><strong>${esc(t('reduceMotion'))}</strong><p>${esc(t('reduceMotionNote'))}</p></div><input type="checkbox" class="switch" id="motion-setting" ${U.read('motion',false)?'checked':''}></label><div class="setting-row"><div><strong>${esc(t('models'))}</strong><p>${state.modelIds.map(id=>esc(CouncilConfig.getVariant(id,state.modelVersions[id]).name)).join(' · ')}</p></div><button class="button subtle" id="settings-models">${esc(t('edit'))}</button></div></section><section class="settings-section"><h2>${esc(t('data'))}</h2><label class="setting-row"><div><strong>${esc(t('rememberText'))}</strong><p>${esc(t('rememberTextNote'))}</p></div><input class="switch" type="checkbox" id="remember-setting" ${U.read('remember-text',false)?'checked':''}></label><div class="setting-row"><div><strong>${esc(t('downloadData'))}</strong><p>${esc(t('localExportNote'))}</p></div><button class="button subtle" id="settings-export">${esc(t('download'))}</button></div><div class="setting-row"><div><strong>${esc(t('localData'))}</strong><p>${esc(t('localDataNote'))}</p></div><button class="button subtle danger" id="clear-local">${esc(t('delete'))}</button></div></section><a class="text-link" href="privacy.html">${esc(t('privacy'))} →</a>`;el.querySelector('#motion-setting').onchange=e=>{U.write('motion',e.target.checked);U.motion();};el.querySelector('#remember-setting').onchange=e=>{U.write('remember-text',e.target.checked);if(!e.target.checked)U.write('threads-v2',localHistory().filter(x=>x.kind==='example').map(({answers,prompt,...x})=>x));renderSidebar();};el.querySelector('#settings-models').onclick=()=>U.modelPicker(state.modelIds,(ids,versions)=>{saveModels(ids,versions);render();},state.modelVersions);el.querySelector('#settings-export').onclick=()=>U.download('council-history.json',JSON.stringify(localHistory(),null,2),'application/json');el.querySelector('#clear-local').onclick=async()=>{if(!await U.confirm(t('clearData'),t('clearConfirm')))return;try{for(const store of [localStorage,sessionStorage])for(const key of Object.keys(store))if(key.startsWith(U.prefix))store.removeItem(key);}catch{U.toast(t('storageError'));return;}state.q='';state.context='';state.modelIds=[...CouncilConfig.defaults];state.modelVersions=CouncilConfig.normalizeVersions({});state.thread=null;render();U.toast(t('cleared'));};}
 function renderProfile(el){const session=CouncilSession.current,user=session?.user;el.innerHTML=pageHeader('profile')+`<nav class="account-pages"><a href="settings.html">${esc(t('general'))}</a><a class="active" href="profile.html">${esc(t('account'))}</a></nav>${user?'':`<div class="empty-state" style="margin-bottom:30px">${icon('user')}<h2>${esc(t('accountNeeded'))}</h2><a class="button dark" href="login.html">${esc(t('login'))}</a></div>`}<section class="profile-card"><div class="profile-header"><span class="avatar large">${user?esc((user.name||user.email||'C').slice(0,1).toUpperCase()):icon('user')}</span><div><h2>${esc(user?.name||t('profile'))}</h2>${user?.emailVerified?`<span class="badge">${esc(t('verified'))}</span>`:''}</div></div><form class="profile-form" id="profile-form"><div class="field"><label for="profile-name">${esc(t('displayName'))}</label><input id="profile-name" name="name" autocomplete="name" maxlength="100" value="${esc(user?.name||'')}" ${user?'required':'disabled'}></div><div class="field"><label for="profile-email">${esc(t('email'))}</label><input id="profile-email" type="email" value="${esc(user?.email||'')}" readonly></div><button class="button dark" type="submit" ${user?'':'disabled'}>${esc(t('save'))}</button></form></section><h2 class="section-title">${esc(t('security'))}</h2><div class="section-panel"><div class="setting-row"><strong>${esc(t('password'))}</strong><a class="button subtle" href="forgot-password.html">${esc(t('edit'))}</a></div><div class="setting-row"><strong>${esc(t('sessions'))}</strong><button class="button subtle" data-account-action="account.sessions.revoke" ${user?'':'disabled'}>${esc(t('continue'))}</button></div></div><h2 class="section-title">${esc(t('data'))}</h2><div class="section-panel"><div class="setting-row"><strong>${esc(t('dataExport'))}</strong><button class="button subtle" data-account-action="account.export" ${user?'':'disabled'}>${esc(t('download'))}</button></div><div class="setting-row"><strong>${esc(t('accountDelete'))}</strong><button class="button subtle danger" data-account-action="account.delete" ${user?'':'disabled'}>${esc(t('delete'))}</button></div></div>${user?`<div class="question-actions"><button class="button subtle" data-account-action="auth.logout">${esc(t('logout'))}</button></div>`:''}`;
  el.querySelector('#profile-form').onsubmit=async e=>{e.preventDefault();if(!user)return;if(!CouncilActions.connected('profile.update')){U.notice(t('profile'),t('endpointMissing'));return;}const button=e.target.querySelector('button');button.disabled=true;try{const result=await CouncilActions.run('profile.update',{name:el.querySelector('#profile-name').value.trim()});if(!result?.user)throw new Error();CouncilSession.accept({authenticated:true,user:result.user});U.toast(t('profileSaved'));}catch{U.toast(t('networkError'));}finally{button.disabled=false;}};el.querySelectorAll('[data-account-action]').forEach(b=>b.onclick=()=>accountAction(b.dataset.accountAction,b));}
 async function accountAction(action,button){if(!CouncilActions.connected(action)){U.notice(t('account'),t('endpointMissing'));return;}if(action==='account.delete'&&!await U.confirm(t('accountDelete'),t('accountDeleteConfirm')))return;button.disabled=true;try{const r=await CouncilActions.run(action,{});if(action==='auth.logout'){if(!r?.signedOut)throw new Error();CouncilSession.accept(null);state.cloud=[];state.thread=null;location.href='index.html';}else if(action==='account.export'){if(!r?.data)throw new Error();U.download('council-account.json',JSON.stringify(r.data,null,2),'application/json');}else{if(!r?.accepted)throw new Error();U.toast(t('requestSent'));}}catch{U.toast(t('operationNotConfirmed'));}finally{button.disabled=false;}}
 async function loadCloud(){const sessionId=CouncilSession.current?.user.id;state.cloud=[];state.cloudLoaded=false;if(CouncilSession.current&&CouncilActions.connected('history.list')){try{const r=await CouncilActions.run('history.list',{});if(CouncilSession.current?.user.id!==sessionId)return;if(Array.isArray(r?.items))state.cloud=r.items.filter(x=>typeof x.id==='string'&&typeof x.title==='string'&&Number.isFinite(x.time)&&Number.isFinite(new Date(x.time).getTime())).map(x=>({...x,cloud:true}));state.cloudLoaded=true;}catch{}}render();const id=new URLSearchParams(location.search).get('thread');if(id&&!state.thread)openThread(id);}
 let gateDismissed=false,gateSilent=false;
function paintGate(d){const back=encodeURIComponent(location.pathname+location.search);d.innerHTML=`<header class="dialog-head"><h2 id="gate-title">${esc(t('gateTitle'))}</h2><button type="button" class="icon-button" data-gate-close aria-label="${esc(t('close'))}">${icon('close')}</button></header><div class="dialog-body"><p id="gate-lead" class="gate-lead">${esc(t('gateLead'))}</p><div class="gate-actions"><a class="button dark" href="signup.html?returnTo=${back}">${esc(t('gateSignup'))}</a><a class="button subtle" href="login.html?returnTo=${back}">${esc(t('gateSignin'))}</a></div></div>`;d.setAttribute('aria-labelledby','gate-title');d.setAttribute('aria-describedby','gate-lead');d.querySelector('[data-gate-close]').onclick=()=>d.close();}
function openGate(force){if(page==='help'||!document.body.classList.contains('workspace'))return;if(CouncilSession.current){const open=document.getElementById('council-gate');if(open?.open){gateSilent=true;open.close();}gateDismissed=false;return;}if(gateDismissed&&!force)return;let d=document.getElementById('council-gate');if(!d){d=document.createElement('dialog');d.id='council-gate';d.className='dialog gate-dialog';document.body.append(d);d.addEventListener('cancel',e=>{e.preventDefault();d.close();});d.addEventListener('close',()=>{document.body.classList.remove('modal-open');if(!gateSilent)gateDismissed=true;gateSilent=false;});}const was=d.open;paintGate(d);if(!was){d.showModal();document.body.classList.add('modal-open');d.querySelector('.button.dark')?.focus();}}
document.addEventListener('DOMContentLoaded',()=>{if(U.read('sidebar-collapsed',false))document.body.classList.add('sidebar-collapsed');render();const params=new URLSearchParams(location.search),id=params.get('thread');if(page==='beta'&&id)openThread(id);else if(page==='beta'&&E.ids.includes(params.get('preset')))prefill(params.get('preset'));openGate(false);});
 document.addEventListener('council:before-language',capture);document.addEventListener('council:language',()=>{const turn=state.thread?.turns.findLast(x=>x.example);if(turn&&!turn.editing&&!turn.customPrompt)turn.prompt='';render();const gate=document.getElementById('council-gate');if(gate?.open)paintGate(gate);});document.addEventListener('council:session',()=>{openGate(false);loadCloud();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]'))document.body.classList.remove('sidebar-mobile-open');});window.addEventListener('pagehide',()=>{capture();cancelRun();U.write('draft-v2',{q:state.q,context:state.context,web:state.web},true);});
})();
