(() => {
 'use strict';
 const I=CouncilI18n,t=I.t, prefix='council-beta:';
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const paths={panel:'M4 4h16v16H4zM9 4v16',plus:'M12 5v14M5 12h14',search:'M10.5 4a6.5 6.5 0 1 0 0 13a6.5 6.5 0 0 0 0-13M16 16l5 5',settings:'M12 8a4 4 0 1 0 0 8a4 4 0 0 0 0-8M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z',wallet:'M4 6h15a2 2 0 0 1 2 2v11H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2l13-2v4M16 11h5v4h-5z',user:'M12 3a4 4 0 1 0 0 8a4 4 0 0 0 0-8M4 21v-2a8 8 0 0 1 16 0v2',arrow:'M12 19V5M5 12l7-7 7 7',chevron:'m9 5 7 7-7 7',attach:'m8 12 6-6a3 3 0 0 1 4 4l-9 9a5 5 0 0 1-7-7L13 1',globe:'M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0M3 12h18M12 3c5 5 5 13 0 18c-5-5-5-13 0-18',check:'m5 12 4 4L20 5',close:'m6 6 12 12M6 18 18 6',copy:'M8 8h12v13H8zM16 8V3H3v13h5',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',more:'M5 12h.01M12 12h.01M19 12h.01',trash:'M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7',message:'M4 4h16v13H8l-4 4z',help:'M12 21a9 9 0 1 0 0-18a9 9 0 0 0 0 18M9 8a3 3 0 0 1 6 1c0 2-3 2-3 5M12 17h.01',file:'M5 2h9l5 5v15H5zM14 2v6h5M8 12h8m-8 4h8',stop:'M6 6h12v12H6z',edit:'m4 16 12-12 4 4L8 20H4z',lock:'M5 10h14v11H5zM8 10V6a4 4 0 0 1 8 0v4'};
 const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.message}"/></svg>`;
 function languages(){return `<div class="languages" role="group" aria-label="${esc(t('language'))}">${[['ru','RU','Русский'],['en','EN','English'],['zh','中文','中文']].map(([code,label,title])=>`<button type="button" data-lang="${code}" lang="${code}" aria-label="${title}" aria-pressed="${I.lang===code}">${label}</button>`).join('')}</div>`;}
 function read(key,fallback,session=false){try{const raw=(session?sessionStorage:localStorage).getItem(prefix+key);return raw===null?fallback:JSON.parse(raw);}catch{return fallback;}}
 function write(key,value,session=false){try{(session?sessionStorage:localStorage).setItem(prefix+key,JSON.stringify(value));return true;}catch{toast(t('storageError'));return false;}}
 function remove(key,session=false){try{(session?sessionStorage:localStorage).removeItem(prefix+key);}catch{}}
 let toastTimer;
 function toast(message){let el=document.getElementById('toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,5000);}
 let returnFocus=null;
 function closeDialog(){const d=document.getElementById('council-dialog');if(d?.open)d.close();}
 function dialog(title,body,{onOpen,wide=false}={}){closeDialog();let d=document.getElementById('council-dialog');if(!d){d=document.createElement('dialog');d.id='council-dialog';d.className='dialog';document.body.append(d);d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.addEventListener('close',()=>{document.body.classList.remove('modal-open');if(returnFocus?.isConnected)returnFocus.focus();});}returnFocus=document.activeElement;d.classList.toggle('dialog-wide',wide);d.innerHTML=`<header class="dialog-head"><h2 id="dialog-title">${esc(title)}</h2><button type="button" class="icon-button" data-close aria-label="${esc(t('close'))}">${icon('close')}</button></header><div class="dialog-body">${body}</div>`;d.setAttribute('aria-labelledby','dialog-title');d.querySelector('[data-close]').onclick=()=>d.close();d.showModal();document.body.classList.add('modal-open');onOpen?.(d);return d;}
 function notice(title,message){return dialog(title,`<p class="muted prose">${esc(message)}</p><div class="dialog-actions"><button class="button dark" data-close-body>${esc(t('done'))}</button></div>`,{onOpen:d=>d.querySelector('[data-close-body]').onclick=closeDialog});}
 async function confirm(title,message){return new Promise(resolve=>{let answered=false;const d=dialog(title,`<p class="muted prose">${esc(message)}</p><div class="dialog-actions"><button class="button subtle" data-no>${esc(t('cancel'))}</button><button class="button danger" data-yes>${esc(t('delete'))}</button></div>`);d.querySelector('[data-no]').onclick=()=>d.close();d.querySelector('[data-yes]').onclick=()=>{answered=true;d.close();};d.addEventListener('close',()=>resolve(answered),{once:true});});}
 async function copy(text){try{await navigator.clipboard.writeText(text);toast(t('copied'));return true;}catch{notice(t('copy'),t('copyError'));return false;}}
 function download(name,text,type='text/plain;charset=utf-8'){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
 function modelMark(id){const m=CouncilConfig.models.find(m=>m.id===id);return m?`<span class="model-mark"><img src="${esc(m.image)}" alt="" width="24" height="24" loading="lazy"></span>`:'';}
 function modelOptions(selection,versions,scope='picker'){
  return CouncilConfig.models.map(m=>{const selected=selection.includes(m.id),v=CouncilConfig.getVariant(m.id,versions[m.id]);return `<section class="model-choice" data-family="${m.id}"><label class="model-option">${modelMark(m.id)}<span><strong>${esc(m.name)}</strong><small>${esc(m.provider)}</small></span><input type="checkbox" data-family-choice value="${m.id}" ${selected?'checked':''}></label><div class="model-version-field"><label class="sr-only" for="${scope}-${m.id}">${esc(t('modelVersion'))} · ${esc(m.name)}</label><select id="${scope}-${m.id}" data-version="${m.id}" ${selected?'':'disabled'}>${CouncilConfig.variants.filter(v=>v.familyId===m.id).map(v=>`<option value="${v.id}" ${versions[m.id]===v.id?'selected':''}>${esc(v.name)}</option>`).join('')}</select><p data-version-note>${esc(t(v.note))}</p></div></section>`;}).join('');
 }
 function bindModelOptions(container,onChange=()=>{}){
  container.querySelectorAll('[data-family-choice],[data-version]').forEach(control=>control.onchange=()=>{
   const row=control.closest('[data-family]'),select=row.querySelector('[data-version]');select.disabled=!row.querySelector('[data-family-choice]').checked;
   const v=CouncilConfig.getVariant(row.dataset.family,select.value);row.querySelector('[data-version-note]').textContent=v?t(v.note):'';onChange();
  });
 }
 function readModelOptions(container){return {ids:[...container.querySelectorAll('[data-family-choice]:checked')].map(x=>x.value),versions:Object.fromEntries([...container.querySelectorAll('[data-version]')].map(x=>[x.dataset.version,x.value]))};}
 function modelPicker(selection,callback,versions=CouncilConfig.normalizeVersions(read('model-versions',{}))){
  const content=`<p class="model-picker-note">${esc(t('modelPickerNote'))}</p><div class="model-options">${modelOptions(selection,versions)}</div><p class="form-error" id="model-error" role="alert" hidden></p><div class="dialog-actions"><button class="button dark" data-apply>${esc(t('done'))}</button></div><p class="micro muted">${esc(t('modelCatalogNote'))}</p>`;
  dialog(t('modelPickerTitle'),content,{onOpen:d=>{bindModelOptions(d,()=>d.querySelector('#model-error').hidden=true);d.querySelector('[data-apply]').onclick=()=>{const {ids,versions}=readModelOptions(d);if(!CouncilConfig.validVersions(ids,versions)){const e=d.querySelector('#model-error');e.hidden=false;e.textContent=t('minOne');return;}callback(ids,versions);closeDialog();};}});
 }
 let session=null,status='checking',generation=0,refreshing=null;
 function emitSession(){document.dispatchEvent(new CustomEvent('council:session',{detail:{status}}));}
 function acceptSession(value){generation++;if(!value?.authenticated||!value.user||typeof value.user.id!=='string'||!value.user.id){session=null;status='guest';}else{session={authenticated:true,user:{id:value.user.id,name:String(value.user.name||''),email:String(value.user.email||''),emailVerified:value.user.emailVerified===true}};status='authenticated';}emitSession();return session;}
 async function refreshSession(){if(!CouncilActions.connected('session.get')){status=session?'authenticated':'guest';emitSession();return session;}if(refreshing)return refreshing;const gen=generation;status='checking';emitSession();refreshing=(async()=>{try{const value=await CouncilActions.run('session.get',{});if(gen!==generation)return session;if(value&&value.authenticated===false)return acceptSession(null);if(value?.authenticated&&typeof value.user?.id==='string'&&value.user.id)return acceptSession(value);status='error';emitSession();return session;}catch{if(gen!==generation)return session;status='error';emitSession();return session;}finally{refreshing=null;}})();return refreshing;}
 const Session=Object.freeze({get current(){return session;},get status(){return status;},accept:acceptSession,refresh:refreshSession});
 function safeReturn(value){if(typeof value!=='string'||/\\|\/\//.test(value))return null;try{const u=new URL(value,location.origin);if(u.origin!==location.origin)return null;const file=u.pathname.split('/').pop();if(file&&!/^(index|beta|models|history|balance|settings|profile|checkout|welcome)\.html$/.test(file)&&u.pathname!=='/')return null;return u.pathname+u.search;}catch{return null;}}
 async function continueWithGoogle(button,returnTo){const next=safeReturn(returnTo)||'index.html';if(!CouncilActions.connected('auth.google')){notice(t('welcomeTitle'),t('googleUnavailable'));return;}button.disabled=true;try{const result=await CouncilActions.run('auth.google',{returnTo:next});if(result?.redirect){const url=safeUrl(result.redirect);if(!url||new URL(url).protocol!=='https:')throw new Error('Invalid redirect');location.assign(url);return;}if(!acceptSession(result)){notice(t('welcomeTitle'),t('authMissingSession'));return;}location.assign(next);}catch{notice(t('welcomeTitle'),t('googleUnavailable'));}finally{if(button?.isConnected)button.disabled=false;}}
 function sessionLink(){return session?`<a href="profile.html" class="account-link"><span class="avatar">${esc((session.user.name||session.user.email||'C').slice(0,1).toUpperCase())}</span><span>${esc(session.user.name||t('profile'))}</span></a>`:document.body.classList.contains('workspace')?`<button type="button" class="account-link" data-open-gate>${icon('user')}<span>${esc(t('login'))}</span></button>`:`<a href="login.html" class="account-link">${icon('user')}<span>${esc(t('login'))}</span></a>`;}
 function format(n){return new Intl.NumberFormat(I.locale,{maximumFractionDigits:0}).format(n);}
 function money(n){return new Intl.NumberFormat(I.locale,{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:n<.01?6:4}).format(n);}
 function safeUrl(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
 function motion(){document.documentElement.classList.toggle('reduce-motion',read('motion',false)===true);}
 globalThis.CouncilUI=Object.freeze({t,esc,icon,languages,read,write,remove,toast,dialog,closeDialog,notice,confirm,copy,download,modelMark,modelOptions,bindModelOptions,readModelOptions,modelPicker,sessionLink,continueWithGoogle,safeReturn,format,money,safeUrl,motion,prefix});globalThis.CouncilSession=Session;
 document.addEventListener('DOMContentLoaded',()=>{motion();document.querySelectorAll('[data-language-control]').forEach(el=>el.innerHTML=languages());document.querySelectorAll('[data-account-control]').forEach(el=>el.innerHTML=sessionLink());refreshSession();});
 document.addEventListener('council:session',()=>document.querySelectorAll('[data-account-control]').forEach(el=>el.innerHTML=sessionLink()));
 document.addEventListener('council:language',()=>{closeDialog();document.querySelectorAll('[data-language-control]').forEach(el=>el.innerHTML=languages());document.querySelectorAll('[data-account-control]').forEach(el=>el.innerHTML=sessionLink());});
 (()=>{
  const host=location.hostname;
  if(host!=='meridianapp.ru'&&host!=='www.meridianapp.ru'&&host!=='cabinet.meridianapp.ru')return;
  const base='https://cabinet.meridianapp.ru';
  CouncilActions.connect({'session.get':async()=>{const r=await fetch(base+'/auth/session',{credentials:'include'});if(r.status===401)return {authenticated:false};if(!r.ok)throw new Error('session');return r.json();},'auth.google':async({returnTo})=>{const url=new URL(base+'/auth/google/start');url.searchParams.set('return_to',new URL(returnTo||'/',location.origin).href);return {redirect:url.href};},'auth.logout':async()=>{const r=await fetch(base+'/auth/logout',{method:'POST',credentials:'include'});if(!r.ok)throw new Error('logout');return {signedOut:true};}});
 })();
})();
