/* Local text extraction only. No upload, cloud storage, or silent truncation. */
(() => {
 'use strict';
 const MAX_BYTES=10*1024*1024,MAX_CHARS=2000000,MAX_FILES=8;
 const error=code=>Object.assign(new Error(code),{code});
 function extension(name){return String(name).split('.').pop().toLowerCase();}
 function validate(file){if(!file||file.size>MAX_BYTES)throw error('fileLarge');if(!['txt','md','csv','json','pdf','docx'].includes(extension(file.name)))throw error('fileUnsupported');}
 async function inflate(data,limit){if(typeof DecompressionStream==='undefined')throw error('fileReadError');const stream=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'));const reader=stream.getReader();let size=0;const chunks=[];try{while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>limit){await reader.cancel();throw error('filesTextLarge');}chunks.push(value);}}finally{reader.releaseLock();}const out=new Uint8Array(size);let pos=0;for(const v of chunks){out.set(v,pos);pos+=v.length;}return out;}
 async function docx(buffer){const data=new Uint8Array(buffer),dv=new DataView(buffer);let eocd=-1;for(let n=data.length-22;n>=Math.max(0,data.length-65557);n--){if(dv.getUint32(n,true)===0x06054b50){eocd=n;break;}}if(eocd<0)throw error('fileReadError');const entries=dv.getUint16(eocd+10,true);if(entries>4000)throw error('fileReadError');let p=dv.getUint32(eocd+16,true),target=null;const decoder=new TextDecoder();for(let n=0;n<entries;n++){if(p+46>data.length||dv.getUint32(p,true)!==0x02014b50)throw error('fileReadError');const nameLen=dv.getUint16(p+28,true),extra=dv.getUint16(p+30,true),comment=dv.getUint16(p+32,true);const name=decoder.decode(data.subarray(p+46,p+46+nameLen));if(name==='word/document.xml'){target={flags:dv.getUint16(p+8,true),method:dv.getUint16(p+10,true),compressed:dv.getUint32(p+20,true),size:dv.getUint32(p+24,true),offset:dv.getUint32(p+42,true)};break;}p+=46+nameLen+extra+comment;}
  if(!target||target.flags&1||target.size>20*1024*1024)throw error('fileReadError');p=target.offset;if(p+30>data.length||dv.getUint32(p,true)!==0x04034b50)throw error('fileReadError');const start=p+30+dv.getUint16(p+26,true)+dv.getUint16(p+28,true);if(start+target.compressed>data.length)throw error('fileReadError');const body=data.subarray(start,start+target.compressed);const xml=decoder.decode(target.method===0?body:target.method===8?await inflate(body,20*1024*1024):(()=>{throw error('fileReadError');})());if(/<!DOCTYPE|<!ENTITY/i.test(xml))throw error('fileReadError');const tree=new DOMParser().parseFromString(xml,'application/xml');if(tree.querySelector('parsererror'))throw error('fileReadError');return [...tree.getElementsByTagNameNS('*','p')].map(p=>[...p.getElementsByTagNameNS('*','t')].map(t=>t.textContent).join('')).join('\n');
 }
 let pdfModule;
 async function pdf(buffer){pdfModule ||= import('./vendor/pdfjs/pdf.min.mjs');const lib=await pdfModule;lib.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdfjs/pdf.worker.min.mjs',document.baseURI).href;const task=lib.getDocument({data:new Uint8Array(buffer),isEvalSupported:false,useSystemFonts:false,disableFontFace:true,cMapUrl:new URL('./vendor/pdfjs/cmaps/',document.baseURI).href,cMapPacked:true,standardFontDataUrl:new URL('./vendor/pdfjs/standard_fonts/',document.baseURI).href});let timeout;try{const doc=await Promise.race([task.promise,new Promise((_,reject)=>{timeout=setTimeout(()=>{task.destroy();reject(error('fileReadError'));},20000);})]);if(doc.numPages>1200)throw error('filesTextLarge');let parts=[],length=0;for(let p=1;p<=doc.numPages;p++){const page=await doc.getPage(p);const content=await page.getTextContent();const text=content.items.map(x=>(x.str||'')+(x.hasEOL?'\n':' ')).join('');length+=text.length;if(length>MAX_CHARS)throw error('filesTextLarge');parts.push(text);page.cleanup();}return parts.join('\n\n');}finally{clearTimeout(timeout);await task.destroy();}}
 async function read(file){validate(file);let text;try{const ext=extension(file.name);text=ext==='pdf'?await pdf(await file.arrayBuffer()):ext==='docx'?await docx(await file.arrayBuffer()):await file.text();}catch(e){throw e.code?e:Object.assign(error('fileReadError'),{cause:e});}text=text.replace(/\u0000/g,'').trim();if(!text)throw error('fileEmpty');if(text.length>MAX_CHARS)throw error('filesTextLarge');return {id:globalThis.crypto?.randomUUID?.()||'f'+Date.now()+Math.random().toString(16).slice(2),name:String(file.name).slice(0,250),size:file.size,type:extension(file.name),text,chars:text.length};}
 globalThis.CouncilFiles=Object.freeze({read,validate,MAX_BYTES,MAX_CHARS,MAX_FILES});
})();
